#!/bin/bash
#Download, compile, and install fldigi applications

#Enable source
cp /etc/apt/sources.list /etc/apt/sources.list.bak
sed -i -e 's/#deb-src/deb-src/g' /etc/apt/sources.list

#Install/update aptitude
apt-get install aptitude -y
aptitude update -y

#Ensure build tools are present
aptitude install build-essential -y

#Start downloading dependencies for flrig
aptitude build-dep flrig fldigi flamp flwrap -y

#Install pavucontrol
apt-get install pavucontrol -y

#Increase swap file size
cp /etc/dphys-swapfile /etc/dphys-swapfile.bak
sed -i -e 's/CONF_SWAPSIZE=100/CONF_SWAPSIZE=1024/g' /etc/dphys-swapfile
/etc/init.d/dphys-swapfile stop
/etc/init.d/dphys-swapfile start

#Install flrig
cd ../build
wget http://www.w1hkj.com/files/flrig/flrig-1.3.49.tar.gz
tar -zxvf ./flrig-1.3.49.tar.gz
cd flrig-1.3.49
./configure
make
make install

#Install fldigi
cd ..
wget http://www.w1hkj.com/files/fldigi/fldigi-4.1.09.tar.gz
tar -zxvf ./fldigi-4.1.09.tar.gz
cd fldigi-4.1.09
./configure
make
make install

#Install flwrap
cd ..
wget http://www.w1hkj.com/files/flwrap/flwrap-1.3.5.tar.gz
tar -zxvf ./flwrap-1.3.5.tar.gz
cd flwrap-1.3.5
./configure
make
make install

#Install flamp
cd ..
wget http://www.w1hkj.com/files/flamp/flamp-2.2.05.tar.gz
tar -zxvf ./flamp-2.2.05.tar.gz
cd flamp-2.2.05
./configure
make
make install

#Change swap file size back to default
sed -i -e 's/CONF_SWAPSIZE=1024/CONF_SWAPSIZE=100/g' /etc/dphys-swapfile
/etc/init.d/dphys-swapfile stop
/etc/init.d/dphys-swapfile start
