#!/bin/bash
#Script to configure GPS dongle as a clock source

#Let's make sure the system is up to date
apt-get update -y
apt-get upgrade -y

#Install necessary gps and chrony daemons
apt-get install gpsd gpsd-clients python-gps chrony -y

#Copy config files
cp ../config/gpsd /etc/default/gpsd
cp ../config/chrony.conf /etc/chrony/chrony.conf

#reboot
echo 'rebooting host, installation complete'
reboot
