#!/bin/bash
#Script to configure GPS dongle as a clock source

#Let's make sure the system is up to date
apt-get update -y
apt-get upgrade -y

#Install necessary gps and chrony daemons
apt-get install gpsd gpsd-clients python-gps chrony -y
