#!/bin/bash
#Download and install js8call

cd ../build
#wget http://files.js8call.com/1.1.0/js8call_1.1.0_armhf.deb
#wget http://files.js8call.com/2.0.0/js8call_2.0.0_armhf.deb
wget http://files.js8call.com/2.1.1/js8call_2.1.1_armhf.deb
#dpkg -i ./js8call_1.1.0_armhf.deb
#dpkg -i ./js8call_2.0.0_armhf.deb
dpkg -i ./js8call_2.1.1_armhf.deb
apt-get install -f -y
