#!/bin/bash
#Master installation script

apt-get update -y
apt-get upgrade -y

./gpsclock-install
./autohotspot-install
./hamlib-install
./flapps-install
./wsjtx-install
./js8call-install
./pat-install
./piardopc-install
./ad2-waveforms-install
./sdr-install

reboot
