#!/bin/bash
#Master installation script

apt-get update -y
apt-get upgrade -y

./gpsclock-install
./autohotspot-install
./hamlib-install
./flrig-install
./fldigi-install
./wsjtx-install
./js8call-install

reboot
