#!/bin/bash

cd ../build
#wget https://github.com/la5nta/pat/releases/download/v0.8.0/pat_0.8.0_linux_armhf.deb
wget https://github.com/la5nta/pat/releases/download/v0.9.0/pat_0.9.0_linux_armhf.deb
sudo dpkg -i ./pat_0.9.0_linux_armhf.deb
