#!/bin/bash

#Install gqrx-sdr software and prepare rtl-sdr dongle

cp ../config/blacklist-dvb.conf /etc/modprobe.d
cp ../config/20.rtlsdr.rules /etc/udev/rules.d

apt-get install rtl-sdr gqrx-sdr -y
