#!/bin/bash
#Download and install wsjt-x

cd ../build
#wget http://physics.princeton.edu/pulsar/K1JT/wsjtx_2.1.0_armhf.deb
#wget https://physics.princeton.edu/pulsar/K1JT/wsjtx_2.1.2_armhf.deb
#wget https://physics.princeton.edu/pulsar/K1JT/wsjtx_2.2.1_armhf.deb
wget https://www.physics.princeton.edu/pulsar/k1jt/wsjtx_2.2.1_armhf.deb
dpkg -i ./wsjtx_2.2.1_armhf.deb
apt-get install -f -y
