#!/bin/bash

sudo apt-get update
sudo apt-get upgrade

sudo apt-get install build-essential git autoconf automake xorg-dev graphicsmagick gv libmotif-dev libcurl4-openssl-dev gpsman gpsmanshp libpcre3-dev libproj-dev libdb5.3-dev python-dev libax25-dev libwebp-dev shapelib libshp-dev festival festival-dev libgeotiff-dev libwebp-dev libgraphicsmagick1-dev xfonts-100dpi xfonts-75dpi -y

xset +fp /usr/share/fonts/X11/100dpi,/usr/share/fonts/X11/75dpi

cd ../build
git clone https://github.com/Xastir/Xastir.git
cd Xastir
./bootstrap.sh

mkdir build
cd build
../configure CPPFLAGS="-I/usr/include/geotiff"
make
sudo make install
sudo chmod u+s /usr/local/bin/xastir

